---
- tags: roles/anyenv/pyenv
  block:
    - name: install pyenv
      shell: anyenv install pyenv
      args:
        creates: ~/.anyenv/envs/pyenv

    - name: "install python versions into pyenv"
      shell: "bash -lc 'pyenv install {{ item }}'"
      args:
        creates: "~/.anyenv/envs/pyenv/versions/{{ item }}"
      notify: pyenv rehash
      with_items: "{{ roles.anyenv.pyenv.versions }}"

    - name: check current pyenv global version of python2
      shell: "bash -lc 'pyenv global | sed -n 1p'"
      register: pyenv_current_global_version_v2
      changed_when: false

    - name: check current pyenv global version of python3
      shell: "bash -lc 'pyenv global | sed -n 2p'"
      register: pyenv_current_global_version_v3
      changed_when: false

    - name: show current global python versions
      debug:
        msg: "python2: {{ pyenv_current_global_version_v2.stdout }}, python3: {{ pyenv_current_global_version_v3.stdout }}"

    - name: set pyenv global version
      shell: "bash -lc 'pyenv global {{ roles.anyenv.pyenv.global_version_v2 }} {{ roles.anyenv.pyenv.global_version_v3 }}'"
      changed_when: pyenv_current_global_version_v2.stdout != roles.anyenv.pyenv.global_version_v2 or pyenv_current_global_version_v3.stdout != roles.anyenv.pyenv.global_version_v3
      notify: pyenv rehash

    - name: install virtualenv
      easy_install:
        name: virtualenv
        executable: ~/.anyenv/envs/pyenv/shims/easy_install

    - name: install pyenv-virtualenv
      git:
        version: v1.1.3
        repo: https://github.com/pyenv/pyenv-virtualenv.git
        dest: ~/.anyenv/envs/pyenv/plugins/pyenv-virtualenv

    - name: install pips into global python2
      pip:
        name: "{{ item.name }}"
        version: "{{ item.version|default() }}"
        executable: ~/.anyenv/envs/pyenv/shims/pip2
      with_items: "{{ roles.anyenv.pyenv.pips_v2 }}"
      notify: pyenv rehash

    - name: install pips into global python3
      pip:
        name: "{{ item.name }}"
        version: "{{ item.version|default() }}"
        executable: ~/.anyenv/envs/pyenv/shims/pip3
      with_items: "{{ roles.anyenv.pyenv.pips_v3 }}"
      notify: pyenv rehash
