- name: install rake temporary
  become: true
  become_user: root
  package:
    name: rake
    state: present

- name: run rake tasks
  become: true
  become_user: "{{ roles.dotfiles.user_name }}"
  shell: "rake {{ item }}"
  args:
    chdir: "{{ roles.dotfiles.dest }}"
  with_items: "{{ roles.dotfiles.rake_tasks }}"

- name: remove rake
  become: true
  become_user: root
  package:
    name: rake
    state: absent

