---
- tags: roles/common/dotfiles
  block:
    - name: clone dotfiles
      become: true
      become_user: "{{ roles.dotfiles.user_name }}"
      notify: link dotfiles
      register: clone_dotfiles_all
      git:
        repo: "{{ roles.dotfiles.repository }}"
        dest: "{{ roles.dotfiles.dest }}"
        update: yes
