client-local-main:
  hosts:
    client-local-main01:
      ansible_host: 192.168.33.101
      ansible_user: owner
  vars: {}

windows-local-main:
  hosts:
    windows-local-main01:
      ansible_host: 192.168.1.13
      ansible_user: Owner
      ansible_password: "{{ global.encrypted.windows_local_main01_password }}"
      ansible_ssh_port: 5985 # PSにて `winrm enumerate winrm/config/Listener` で表示されるポート
      ansible_connection: winrm


